/// Modifier flags. Bit values match `CGEventFlags` so the macOS layer converts at no cost.
public struct ModifierFlags: OptionSet, Hashable, Codable, Sendable {
    public let rawValue: UInt64
    public init(rawValue: UInt64) { self.rawValue = rawValue }

    /// `kCGEventFlagMaskNonCoalesced`: set on keys injected by key code
    public static let nonCoalesced = ModifierFlags(rawValue: 0x0000_0100)
    public static let capsLock = ModifierFlags(rawValue: 0x0001_0000)
    public static let shift = ModifierFlags(rawValue: 0x0002_0000)
    public static let control = ModifierFlags(rawValue: 0x0004_0000)
    public static let option = ModifierFlags(rawValue: 0x0008_0000)
    public static let command = ModifierFlags(rawValue: 0x0010_0000)
    public static let numericPad = ModifierFlags(rawValue: 0x0020_0000)
    public static let help = ModifierFlags(rawValue: 0x0040_0000)
    public static let function = ModifierFlags(rawValue: 0x0080_0000)

    /// Modifiers that can define a hotkey
    public static let hotkeyMask: ModifierFlags = [.control, .option, .command, .shift]
    /// While any of these is held, the engine does not transform letters
    public static let otherControlMask: ModifierFlags = [.command, .control, .option, .function, .numericPad, .help]
}

/// Normalized keyboard/mouse event, independent of CoreGraphics.
public struct KeyEvent: Equatable, Sendable {
    public enum Kind: Equatable, Sendable {
        case keyDown
        case keyUp
        case flagsChanged
        /// Left/right mouse button down
        case mouseDown
        /// Left/right mouse drag (also starts a new word)
        case mouseDragged
    }

    public var kind: Kind
    /// Mac virtual key code (kVK_*)
    public var keyCode: UInt16
    /// All event flags, including device-dependent bits; hotkey detection compares the raw value
    public var flags: ModifierFlags
    /// When the event arrived, in nanoseconds of system uptime; 0 when unknown (mouse events)
    public var time: UInt64
    /// keyDown generated by holding the key (autorepeat)
    public var isRepeat: Bool

    public init(kind: Kind, keyCode: UInt16 = 0, flags: ModifierFlags = [], time: UInt64 = 0,
                isRepeat: Bool = false) {
        self.kind = kind
        self.keyCode = keyCode
        self.flags = flags
        self.time = time
        self.isRepeat = isRepeat
    }
}

/// Common Mac virtual key codes (Carbon kVK_*).
public enum KeyCode {
    public static let a: UInt16 = 0
    public static let z: UInt16 = 6
    public static let returnKey: UInt16 = 36
    public static let tab: UInt16 = 48
    public static let space: UInt16 = 49
    public static let delete: UInt16 = 51
    public static let escape: UInt16 = 53
    public static let keypadClear: UInt16 = 71
    public static let enter: UInt16 = 76
    public static let home: UInt16 = 115
    public static let forwardDelete: UInt16 = 117
    public static let end: UInt16 = 119
    public static let leftArrow: UInt16 = 123
    public static let rightArrow: UInt16 = 124
    public static let downArrow: UInt16 = 125
}

/// `eventSourceUserData` value marking every event LiteKey injects ("LKEY").
public enum EventMarker {
    public static let value: Int64 = 0x4C4B_4559
}
